### PR TITLE
Improved error handling

### PR DESCRIPTION
**Pull request by rousso**

### CODE REVIEW

**Comment by milioan** [comment]
image
error message displays the object and not the message.
To replicate the issue, click on a tab and close wifi to interrupt the network call

**Comment by milioan** [comment]
image
Unrelated to this PR, but it would be better to close the the quick tour window once we click outside of home tab

**Review by milioan — APPROVED** [review]

**Comment by rousso** [comment]
> image error message displays the object and not the message. To replicate the issue, click on a tab and close wifi to interrupt the network call

Ok. Fixed. jQuery does not always throw Error objects. In case a clear error message cannot be extracted from the trhown object, the error detail will now be hidden.

**Comment by rousso** [comment]
> image Unrelated to this PR, but it would be better to close the quick tour window once we click outside of home tab

To do that we would have to set the trigger of the popover to "focus" which would make it appear beyond the context of the tour, unless we make the tour logic more complex. So, I dropped the idea and added a "Cancel" button instead. It is good enough as it is.

**Pull request merged**
